name: Unzip File

on:
  push:
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Find and Unzip file
        run: |
          ZIP_FILE=$(find . -name "*.zip" | head -n 1)
          if [ -n "$ZIP_FILE" ]; then
            unzip "$ZIP_FILE" -d extracted_files/
            rm "$ZIP_FILE"
          else
            echo "No ZIP file found!"
            exit 1
          fi

      - name: Commit extracted files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add extracted_files/
          git commit -m "Extracted ZIP files"
          git push
